const types = {
  LOGIN_UPDATE: 'LOGIN_UPDATE',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  UPDATE_PASSWORD_CONFIRMATION: 'UPDATE_PASSWORD_CONFIRMATION',
  UPDATE_EMAIL: 'UPDATE_EMAIL',
  UPDATE_NAME: 'UPDATE_NAME',
};

export default types;
